### ISSUE TITLE
Patch does not work under proton

### ISSUE THREAD

**Issue by KaiNickson** [VaanaCZ/LANVP#15]
Installing the patch when using proton in linux does not create the .ini file.
My hypothesis is that by default proton uses it's own version of libraries over ones in the game directory

I could make it work however by opening winecfg via protontricks:
`protontricks 110800 winecfg`

And under "Libraries" adding an new override for "dinput8.dll"

After this everything works as described in the readme.
I'll be playing the game some more in the coming days to see if it runs ok.

I don't know if there is a cleaner/easier way to implement this or if there is a possibility to provide these steps in the readme?
I'll be adding a guide to steam soon with these instructions as well if I don't have massive issues while playing the game.

**Comment by VaanaCZ** [comment]
> My hypothesis is that by default proton uses it's own version of libraries over ones in the game directory
...and your hypothesis is right.

> I don't know if there is a cleaner/easier way to implement this or if there is a possibility to provide these steps in the readme?
I don't know of way to fix this directly from within the patch.

An installation guide for Proton has ben added to the readme thanks to @18iteration in the latest commit #14 .

**Comment by KaiNickson** [comment]
Thanks for the swift follow-up

**Comment by Patola** [comment]
I've just bought and installed with Proton 7.0-2 and according to the wiki did the winecfg for dinput.dll. It ran and created lanvp.ini with apparently correct settings, including my ultrawide resolution 2560x1080. However, when I try to run the game, it simply shows a dialog saying "GetdfDIJoystick" where I can only press "[OK]" and it closes. Any hint on how to solve this?

**Comment by Patola** [comment]
Sort of solved it -- I still have that dialog when I press play, but with the command:
`protontricks 110800 d3dx9_43 d3dcompiler_43 d3dx11_43 d3dcompiler_47`
The game starts and plays correctly, with the correct fonts (no tiny menus) and allows me to see movies and cutscenes.
