### ISSUE TITLE
More of a request than an Issue.

### ISSUE THREAD

**Issue by Wickedheadwound** [VaanaCZ/LANVP#16]
I am trying to submit a request on a Job title for truckers, I have seen a lot of tucks around as well as trailers and thought this would be a good idea for a job and that would be a mechanic for the truckers, for when they are broken down or out of gas this mechanic would have a radio connected to the truckers radio that would be able to drive out and repair or refuel. They should also have the ability to clear the trucks out to help the server. Depending on the issue with the truck they would have to pay them or the mechanic can give them a bill in order for them to get paid. So they would be basically DOT but only for the tuckers.

**Comment by wrestlerdude** [comment]
... wtf.
