### ISSUE TITLE
Stuttering with G-Sync

### ISSUE THREAD

**Issue by MaluNoPeleke** [VaanaCZ/LANVP#2]
Thanks a lot for your effort making an old game run smoothly!

Sadly it doesn't help in my case. I have an AMD Ryzen 7 3700X with a GeForce RTX 3060 Ti and 32 GB RAM + a 144 Hz Display which is G-Sync compatible.
Except for the forced resolution (because of https://github.com/VaanaCZ/LANVP/issues/1#issuecomment-841815977) setting everything else is set to default in your config and the ingame settings are all set to maximum including 1080p with 144 FPS.
Do you have any idea why it is stuttering a lot for me or how I could identify the cause?
Thanks in advance.

**Comment by VaanaCZ** [comment]
That sounds really strange.

Personally, I get bad performance when running on DirectX9. Are you sure you are running the game on DirectX 11? You can check by looking in the bottom left corner of the main menu (it should say either _- DX9_ or _- DX11_ at the end). 

If switching APIs doesn't help, then I am not sure how much I can do. 
Do you mean stutter as in low FPS, or are you getting frequent frame drops (microstutter) every couple seconds?

**Comment by MaluNoPeleke** [comment]
I wasn't aware that it is possible to change to DirectX11. It always says DX9 in the game menu. Where/How can I change this?

**Comment by zoli456** [comment]
Go to "%USERPROFILE%\Documents\Rockstar Games\L.A. Noire\" (copy paste). Open settings.ini and change the "Renderer:" value to "DirectX 11".

**Comment by MaluNoPeleke** [comment]
Thanks that did the trick. Maybe you want to mention it in the Readme as well.
