### ISSUE TITLE
Playing On Controller is not good

### ISSUE THREAD

**Issue by Bayomayo0** [VaanaCZ/LANVP#22]
everything about the patch works fine, apart from the config file, but it doesn't seem to change anything, and the controller support. when you drive, the camera looks down, when you press down left stick for siren, it pauses the game. keyboard works fine but the controller doesn't

Edit: i managed to solve the problem, by turning on and off my controller, but now the movement is reversed, and it is also happening to the keyboard

**Comment by Ryusennin** [comment]
Nothing to do with the patch.

**Comment by 18iteration** [comment]
> everything about the patch works fine, apart from the config file, but it doesn't seem to change anything, and the controller support. when you drive, the camera looks down, when you press down left stick for siren, it pauses the game. keyboard works fine but the controller doesn't
> 
> Edit: i managed to solve the problem, by turning on and off my controller, but now the movement is reversed, and it is also happening to the keyboard

The patch is not responsible for what you're describing.
Use Steam's big picture UI to change controller assignment.

Please close the issue unless further support is necessary.

**Comment by VaanaCZ** [comment]
Not related to the patch
