### ISSUE TITLE
When launch getdfdijoystick monit appear

### ISSUE THREAD

**Issue by Tokwone** [VaanaCZ/LANVP#26]
When launch getdfdijoystick monit appear, how to disable this monit?

**Comment by MrEWhite** [comment]
I'm getting the same problem here. Upon launching the game on my Steam Deck, I get a pop up that says that. Clicking "Ok" lets the game launch as usual.

**Comment by f0li083** [comment]
I get the same thing, clicking ok launches the game anyway.

**Comment by tiagogl** [comment]
Same issue here on Batocera with Lutris

**Comment by VaanaCZ** [comment]
Looks like Wine does not implement this function. Should be fixed in the next release.

**Comment by VaanaCZ** [comment]
I do not use Linux or Wine, so someone else capable of producing a valid bug report has to do this. Either way, in the next version I am switching to Ultimate-ASI loader, so this should no longer be a problem.

**Comment by VaanaCZ** [comment]
Fixed with the latest release:
https://github.com/VaanaCZ/LANVP/releases/tag/v2.0

**Comment by Tiagoquix** [comment]
Hello, I can confirm this is fixed. Many thanks for your support!
