### ISSUE TITLE
Provide the "lanvp.ini" file settings in plain text form

### ISSUE THREAD

**Issue by eduazy** [VaanaCZ/LANVP#29]
My game is not generating the lanvp.ini file in the game folder at all. Please provide the default file here in the repo or include the lines of code so we can create the file ourselves.

**Comment by VaanaCZ** [comment]
I apologize for the problem. This will be done with the next release.

**Comment by VaanaCZ** [comment]
Done with the latest release:
https://github.com/VaanaCZ/LANVP/releases/tag/v2.0
