### ISSUE TITLE
dx9 on version 2.0?

### ISSUE THREAD

**Issue by DiogoLZ1** [VaanaCZ/LANVP#37]
There's no way to disable and change dx11 to dx9 anymore? I wanna use sgssaa cuz this game's anti alias sucks, and sgssaa only works with dx9 as far as i know.

**Comment by VaanaCZ** [comment]
There is. Go to `User Folder\Documents\Rockstar Games\L.A. Noire`. There you should find `settings.ini`. Here you just need to change the Renderer from:
`Renderer:DirectX 11`
to
`Renderer:DirectX 9`

If you are playing the Rockstar Launcher version, you might need to do this directly in the launcher instead
`Settings > My Installed Games > L.A. Noire`

If that doesn't work, you can also try the `--dx9` command-line argument.

Hope it helps.

**Comment by DiogoLZ1** [comment]
Thanks a lot! Changing the settings.ini worked perfectly. The game do run a little worse though, with little stutters here and there and a lot of LOD issues (pop ins and the game not rendering high LOD's fast enough). But looks a lot nicer with 8x sgssaa.
